import { ExpenseCategory } from '../../domain/entities/ExpenseCategory';
import { ExpenseCategoryResponseDTO, ExpenseCategoryListResponseDTO, ExpenseCategoryValidationResponseDTO, ExpenseCategoryDeleteResponseDTO } from '../dto/ExpenseCategoryResponseDTO';

export class ExpenseCategoryMapper {
  static toDomainFromCreateRequest(tenantId: string, data: { name: string; code: string; is_private?: boolean }): ExpenseCategory {
    return new ExpenseCategory(
      '', // id will be generated by Prisma
      tenantId,
      data.name,
      data.code.toUpperCase(),
      data.is_private || false,
      new Date()
    );
  }

  static toResponseDTO(expenseCategory: ExpenseCategory): ExpenseCategoryResponseDTO {
    return {
      id: expenseCategory.id,
      tenant_id: expenseCategory.tenantId,
      name: expenseCategory.name,
      code: expenseCategory.code,
      is_private: expenseCategory.isPrivate,
      created_at: expenseCategory.createdAt.toISOString(),
    };
  }

  static toListResponseDTO(
    categories: ExpenseCategory[],
    total: number,
    page: number,
    limit: number
  ): ExpenseCategoryListResponseDTO {
    return {
      data: categories.map(category => this.toResponseDTO(category)),
      total,
      page,
      limit,
      total_pages: Math.ceil(total / limit),
    };
  }

  static toValidationResponseDTO(isValid: boolean, message?: string): ExpenseCategoryValidationResponseDTO {
    return {
      is_valid: isValid,
      message,
    };
  }

  static toDeleteResponseDTO(success: boolean, message: string): ExpenseCategoryDeleteResponseDTO {
    return {
      success,
      message,
    };
  }
}